### ISSUE TITLE
README.md is not consistent about platforms

### ISSUE THREAD

**Issue by dmbates** [JuliaBinaryWrappers/MKL_jll.jl#2]
The _Sources_ section of `README.md` and the code in `src/wrappers` indicate that the package is provided on four platforms but the _Platforms_ section only lists one.

**Comment by giordano** [comment]
Yes, this is unfortunate, but I don't have currently a good solution.  I'm closing this ticket in favour of https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/823, which tracks already this issue
